alert('Hello');
const name = prompt('what is your name ?');
console.log('Name:');
console.log(name);
console.log('Typeof Name:');
console.log(typeof name);
const age = prompt('how old are you ?');
console.log('Age:');
console.log(age);
console.log('Typeof age:');
console.log(typeof age);
const age2 = Number(age);
console.log('Constructor Number Change Age as String to Age as number');
console.log(age2);
console.log('Typeof changes:');
console.log(typeof age2);
console.log('Check with Number.isNaN:');
console.log(Number.isNaN(age2));
const nextYearOld = age2 + 1;
console.log('Nextyearold:');
console.log(nextYearOld);
const doubleYearOld = age2 * 2;
console.log('Doubleyearold:');
console.log(doubleYearOld);
const favouriteNumber = prompt('Your favourite number ?');
console.log('Favourite number:');
console.log(favouriteNumber);
console.log('Typeof Favorite number:');
console.log(typeof favouriteNumber);
console.log('Constructor Number Change String to number');
const favouriteNumber2 = Number(favouriteNumber);
console.log(favouriteNumber2);
console.log(typeof favouriteNumber2);
console.log('-----------------------');
let price = 19.99;
price += 5.5;
console.log(price);
console.log('Use toFixed(1)');
const fixedPrice = price.toFixed(1);
console.log(fixedPrice);
console.log('Typeof:');
console.log(typeof fixedPrice);
console.log('Constructor Number Change String to number');
console.log(Number(fixedPrice));
