alert('Hello');
const name = prompt('what is your name ?');
console.log('Name:');
console.log(name);
console.log('Typeof Name:');
console.log(typeof name);
const age = prompt('how old are you ?');
console.log('Age:');
console.log(age);
console.log('Typeof age:');
console.log(typeof age);
const age2 = Number(age);
console.log('Constructor Number Change Age as String to Age as number');
console.log(age2);
console.log('Typeof changes:');
console.log(typeof age2);
console.log('Check with Number.isNaN:');
console.log(Number.isNaN(age2));
const nextyearold = age2 + 1;
console.log('Nextyearold:');
console.log(nextyearold);
const doubleyearold = age2 * 2;
console.log('Doubleyearold:');
console.log(doubleyearold);
console.log('-----------------------');
let price = 19.99;
price += 5.5;
console.log(price);
console.log('Use toFixed(1)');
const fixedprice = price.toFixed(1);
console.log(fixedprice);
console.log('Typeof:');
console.log(typeof fixedprice);
console.log('Constructor Number Change String to number');
console.log(Number(fixedprice));
